# Site Settings
remote_theme             : "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin    : "default"
locale                   : "en-US"
title                    : "Sungjin Bae, Ph.D."
title_separator          : "-"
name                     : "Sungjin Bae"
description              : "Postdoctoral researcher in rehabilitation robotics and neurorehabilitation at Northwestern University & Shirley Ryan AbilityLab."
url                      : "https://sonjin1128.github.io"
repository               : "sonjin1128/sonjin1128.github.io"
search                   : true

# Build settings
markdown: kramdown
highlighter: rouge
timezone: America/Chicago

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

# Author profile (left sidebar)
author:
  name             : "Sungjin Bae, Ph.D."
  avatar           : "/assets/images/profile.jpg"
  bio              : "Postdoctoral Researcher in rehabilitation robotics & neurorehabilitation"
  location         : "Chicago, IL, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sungjin.bae@northwestern.edu"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.co.kr/citations?user=eL3KB-MAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sungjin-bae-778749102/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sonjin1128"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sungjin.bae@northwestern.edu"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.co.kr/citations?user=eL3KB-MAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sungjin-bae-778749102/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sonjin1128"

# Page defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
